# https://docs.codecov.com/docs/codecov-yaml#default-yaml
coverage:
  precision: 0      # Default: 2
  round: down       # Default: down
  range: "80...100" # Default: 70...100
codecov:
    notify:
        after_n_builds: 4
flags:
  unittests:
    carryforward: false
  numberExtensions:
    carryforward: false
  serialization:
    carryforward: false
  compatibility:
    carryforward: false
ignore:
  - "OasysUnitsNet.Tests"
  - "OasysUnitsNet.NumberExtensions.Tests"
  - "OasysUnitsNet.Serialization.JsonNet.CompatibilityTests"
  - "OasysUnitsNet.Serialization.JsonNet.Tests"
  - "Artifacts\OasysUnitsNet.Tests"
  - "Artifacts\OasysUnitsNet.NumberExtensions.Tests"
  - "Artifacts\OasysUnitsNet.Serialization.JsonNet.CompatibilityTests"
  - "Artifacts\OasysUnitsNet.Serialization.JsonNet.Tests"