# https://docs.codecov.com/docs/codecov-yaml#default-yaml
coverage:
  precision: 0      # Default: 2
  round: down       # Default: down
  range: "80...100" # Default: 70...100
codecov:
    notify:
        after_n_builds: 4
flags:
  unittests:
    carryforward: false
  numberExtensions:
    carryforward: false
  serialization:
    carryforward: false
  compatibility:
    carryforward: false
ignore:
  - "UnitsNet.Tests"
  - "UnitsNet.NumberExtensions.Tests"
  - "UnitsNet.Serialization.JsonNet.CompatibilityTests"
  - "UnitsNet.Serialization.JsonNet.Tests"
  - "Artifacts\UnitsNet.Tests"
  - "Artifacts\UnitsNet.NumberExtensions.Tests"
  - "Artifacts\UnitsNet.Serialization.JsonNet.CompatibilityTests"
  - "Artifacts\UnitsNet.Serialization.JsonNet.Tests"